INSERT INTO account(identity, password) values ('user1@email.com', 'password');
INSERT INTO account(identity, password) values ('user2@email.com', 'password');

INSERT INTO MOVIES(title, imdb_rating) values ('Along Came a Spider', 6.4);
INSERT INTO MOVIES(title, imdb_rating) values ('Batman', 7.5);
INSERT INTO MOVIES(title, imdb_rating) values ('Batman & Mr. Freeze: SubZero', 7.22);
INSERT INTO MOVIES(title, imdb_rating) values ('Batman & Robin', 3.8);
INSERT INTO MOVIES(title, imdb_rating) values ('Batman Begins', 8.2);
INSERT INTO MOVIES(title, imdb_rating) values ('Batman Beyond: Return of the Joker', 7.8);
INSERT INTO MOVIES(title, imdb_rating) values ('Batman Beyond: The Movie', 7.8);
INSERT INTO MOVIES(title, imdb_rating) values ('Batman Forever', 5.4);
INSERT INTO MOVIES(title, imdb_rating) values ('Batman Ninja', 5.6);
INSERT INTO MOVIES(title, imdb_rating) values ('Batman Returns', 7.0);
INSERT INTO MOVIES(title, imdb_rating) values ('Batman Unlimited: Animal Instincts', 5.8);
INSERT INTO MOVIES(title, imdb_rating) values ('Batman and Harley Quinn', 5.9);
INSERT INTO MOVIES(title, imdb_rating) values ('Batman v Superman: Dawn of Justice', 6.4);
INSERT INTO MOVIES(title, imdb_rating) values ('Batman vs Teenage Mutant Ninja Turtles', 7.1);
INSERT INTO MOVIES(title, imdb_rating) values ('Batman vs. Robin', 7.1);
INSERT INTO MOVIES(title, imdb_rating) values ('Batman vs. Two-Face', 6.2);
INSERT INTO MOVIES(title, imdb_rating) values ('Batman: Assault on Arkham', 7.5);
INSERT INTO MOVIES(title, imdb_rating) values ('Batman: Bad Blood', 6.8);
INSERT INTO MOVIES(title, imdb_rating) values ('Batman: Dead End', 7.3);
INSERT INTO MOVIES(title, imdb_rating) values ('Batman: Gotham Knight', 6.7);
INSERT INTO MOVIES(title, imdb_rating) values ('Batman: Gotham by Gaslight', 6.7);
INSERT INTO MOVIES(title, imdb_rating) values ('Batman: Hush', 6.9);
INSERT INTO MOVIES(title, imdb_rating) values ('Batman: Mask of the Phantasm', 7.8);
INSERT INTO MOVIES(title, imdb_rating) values ('Batman: Mystery of the Batwoman', 6.7);
INSERT INTO MOVIES(title, imdb_rating) values ('Batman: Return of the Caped Crusaders', 6.7);
INSERT INTO MOVIES(title, imdb_rating) values ('Batman: Soul of the Dragon', 6.1);
INSERT INTO MOVIES(title, imdb_rating) values ('Batman: The Dark Knight Returns, Part 1', 8.0);
INSERT INTO MOVIES(title, imdb_rating) values ('Batman: The Dark Knight Returns, Part 2', 8.4);
INSERT INTO MOVIES(title, imdb_rating) values ('Batman: The Killing Joke', 6.4);
INSERT INTO MOVIES(title, imdb_rating) values ('Batman: The Long Halloween, Part One', 7.3);
INSERT INTO MOVIES(title, imdb_rating) values ('Batman: The Long Halloween, Part Two', 7.2);
INSERT INTO MOVIES(title, imdb_rating) values ('Batman: Under the Red Hood', 8.1);
INSERT INTO MOVIES(title, imdb_rating) values ('Batman: Year One', 7.4);
INSERT INTO MOVIES(title, imdb_rating) values ('Big Ass Spider!', 5.3);
INSERT INTO MOVIES(title, imdb_rating) values ('Captain Morten and the Spider Queen', 5.7);
INSERT INTO MOVIES(title, imdb_rating) values ('David Bowie: Glass Spider', 7.3);
INSERT INTO MOVIES(title, imdb_rating) values ('Earth vs. the Spider', 4.3);
INSERT INTO MOVIES(title, imdb_rating) values ('Eyes of the Spider', 6.5);
INSERT INTO MOVIES(title, imdb_rating) values ('Horrors of Spider Island', 2.6);
INSERT INTO MOVIES(title, imdb_rating) values ('Jack Black: Spider-Man', 7.5);
INSERT INTO MOVIES(title, imdb_rating) values ('Kiss of the Spider Woman', 7.3);
INSERT INTO MOVIES(title, imdb_rating) values ('Lego Batman: The Movie - DC Super Heroes Unite', 6.5);
INSERT INTO MOVIES(title, imdb_rating) values ('Lego Marvel Spider-Man: Vexed by Venom', 5.7);
INSERT INTO MOVIES(title, imdb_rating) values ('Monmon the Water Spider', 7.6);
INSERT INTO MOVIES(title, imdb_rating) values ('Son of Batman', 6.7);
INSERT INTO MOVIES(title, imdb_rating) values ('Spider', 6.8);
INSERT INTO MOVIES(title, imdb_rating) values ('Spider & Rose', 6.8);
INSERT INTO MOVIES(title, imdb_rating) values ('Spider Baby or, the Maddest Story Ever Told', 6.8);
INSERT INTO MOVIES(title, imdb_rating) values ('Spider Lilies', 6.2);
INSERT INTO MOVIES(title, imdb_rating) values ('Spider Man: Lost Cause', 5.2);
INSERT INTO MOVIES(title, imdb_rating) values ('Spider in the Web', 4.5);
INSERT INTO MOVIES(title, imdb_rating) values ('Spider-Ham: Caught in a Ham', 6.2);
INSERT INTO MOVIES(title, imdb_rating) values ('Spider-Man', 7.3);
INSERT INTO MOVIES(title, imdb_rating) values ('Spider-Man 2', 7.4);
INSERT INTO MOVIES(title, imdb_rating) values ('Spider-Man 2: Another World', 7.2);
INSERT INTO MOVIES(title, imdb_rating) values ('Spider-Man 3', 6.2);
INSERT INTO MOVIES(title, imdb_rating) values ('Spider-Man Strikes Back', 5.4);
INSERT INTO MOVIES(title, imdb_rating) values ('Spider-Man Title Reveal', 7.8);
INSERT INTO MOVIES(title, imdb_rating) values ('Spider-Man: Far from Home', 7.4);
INSERT INTO MOVIES(title, imdb_rating) values ('Spider-Man: Homecoming', 7.4);
INSERT INTO MOVIES(title, imdb_rating) values ('Spider-Man: Homecoming, NBA Finals: Watch the Game', 7.5);
INSERT INTO MOVIES(title, imdb_rating) values ('Spider-Man: Into the Spider-Verse', 8.4);
INSERT INTO MOVIES(title, imdb_rating) values ('Spider-Man: No Way Home', 8.7);
INSERT INTO MOVIES(title, imdb_rating) values ('Spider-Man: The Dragon''s Challenge', 5.2);
INSERT INTO MOVIES(title, imdb_rating) values ('Spider-Man: The Lost Avenger', 5.3);
INSERT INTO MOVIES(title, imdb_rating) values ('Spider-Man: The Ultimate Villain Showdown', 7.0);
INSERT INTO MOVIES(title, imdb_rating) values ('Spider-Plant Man', 6.4);
INSERT INTO MOVIES(title, imdb_rating) values ('Superman/Batman: Apocalypse', 7.1);
INSERT INTO MOVIES(title, imdb_rating) values ('Superman/Batman: Public Enemies', 7.2);
INSERT INTO MOVIES(title, imdb_rating) values ('The Amazing Adventures of Spider-Man', 8.6);
INSERT INTO MOVIES(title, imdb_rating) values ('The Amazing Spider-Man', 6.9);
INSERT INTO MOVIES(title, imdb_rating) values ('The Amazing Spider-Man 2', 6.6);
INSERT INTO MOVIES(title, imdb_rating) values ('The Batman Superman Movie: World''s Finest', 7.8);
INSERT INTO MOVIES(title, imdb_rating) values ('The Batman vs. Dracula', 6.6);
INSERT INTO MOVIES(title, imdb_rating) values ('The Death of Spider-Man', 7.5);
INSERT INTO MOVIES(title, imdb_rating) values ('The Giant Spider', 5.4);
INSERT INTO MOVIES(title, imdb_rating) values ('The Giant Spider Invasion', 3.2);
INSERT INTO MOVIES(title, imdb_rating) values ('The Girl and the Spider', 6.2);
INSERT INTO MOVIES(title, imdb_rating) values ('The Itsy Bitsy Spider', 6.1);
INSERT INTO MOVIES(title, imdb_rating) values ('The Legend of Spider Forest', 4.5);
INSERT INTO MOVIES(title, imdb_rating) values ('The Lego Batman Movie', 7.3);
INSERT INTO MOVIES(title, imdb_rating) values ('The Lost Spider Pit Sequence', 7.4);
INSERT INTO MOVIES(title, imdb_rating) values ('The Red Spider', 5.8);
INSERT INTO MOVIES(title, imdb_rating) values ('The Spider', 4.5);
INSERT INTO MOVIES(title, imdb_rating) values ('The Spider Labyrinth', 6.5);
INSERT INTO MOVIES(title, imdb_rating) values ('The Spider Returns', 6.8);
INSERT INTO MOVIES(title, imdb_rating) values ('The Spider Woman', 7.0);
INSERT INTO MOVIES(title, imdb_rating) values ('The Spider Woman Strikes Back', 6.0);
INSERT INTO MOVIES(title, imdb_rating) values ('The Spider and the Fly', 6.8);
INSERT INTO MOVIES(title, imdb_rating) values ('The Spider and the Tulip', 6.7);
INSERT INTO MOVIES(title, imdb_rating) values ('The Vampire Spider', 6.2);
INSERT INTO MOVIES(title, imdb_rating) values ('Web of the Spider', 5.6);

